[project]
name = "tinyrag"
version = "0.1"
description = "A Tiny Agent Workflow AI Application"
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "boto3>=1.39.6",
    "cachetools>=6.1.0",
    "fastapi>=0.115.14",
    "filetype>=1.2.0",
    "granian[reload]>=2.4.2",
    "langchain>=0.3.26",
    "langchain-chroma>=0.2.4",
    "langchain-community>=0.3.27",
    "langchain-milvus>=0.2.1",
    "langchain-ollama>=0.3.3",
    "langchain-openai>=0.3.27",
    "langchain-postgres>=0.0.15",
    "langchain-qdrant>=0.2.0",
    "langgraph>=0.5.0",
    "mypy-boto3-s3>=1.39.5",
    "opendal>=0.46.0",
    "psycopg[python]>=3.2.9",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "pymysql>=1.1.1",
    "pypdf>=5.8.0",
    "python-multipart>=0.0.20",
    "pytz>=2025.2",
    "redis>=6.2.0",
    "requests>=2.32.4",
    "rq>=2.4.0",
    "rq-scheduler>=0.14.0",
    "sqlmodel>=0.0.24",
    "types-cachetools>=6.0.0.20250525",
    "types-pytz>=2025.2.0.20250516",
    "types-requests>=2.32.4.20250611",
    "uvloop>=0.21.0",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
default = true

[dependency-groups]
dev = [
    "coverage>=7.9.1",
    "mypy>=1.16.1",
    "pytest>=8.4.1",
    "ruff>=0.12.1",
]

[tool.mypy]
strict = true
exclude = ["venv", ".venv", "alembic", "app/tests/.*"]

[tool.ruff]
target-version = "py312"
exclude = ["alembic"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG001", # unused arguments in functions
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "W191",  # indentation contains tabs
    "B904",  # Allow raising exceptions without from e, for HTTPException
]

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true
