GET {{url_prefix}}/workflow/list

###
GET {{url_prefix}}/workflow?id=1

###
GET {{url_prefix}}/workflow?id=2

###
POST {{url_prefix}}/workflow
Content-Type: application/json

< ./workflow_demo1.json

###
PUT {{url_prefix}}/workflow
Content-Type: application/json

< ./workflow_demo1.json


###
POST {{url_prefix}}/workflow
Content-Type: application/json

< ./workflow_demo2.json

###
GET {{url_prefix}}/workflow/check_list?id=1
