GET {{url_prefix}}/workflow/run?id=1

###
POST {{url_prefix}}/workflow/run
Content-Type: application/json

{
  "workflow_id": 1
}

###
POST {{url_prefix}}/workflow/run/execute
Content-Type: application/json

{
  "id": 1,
  "input_variables": [
    {
      "name": "query",
      "value": "背一首家喻户晓的唐诗给我"
    }
  ]
}

