GET http://{{origin}}{{api_prefix}}/task/knowledge/list?workspace_id=1
Authorization: Bearer {{auth_token}}

###
GET http://{{origin}}{{api_prefix}}/task?id={{task_id}}
Authorization: Bearer {{auth_token}}
