GET http://{{origin}}{{api_prefix}}/workspace/list
Authorization: Bearer {{auth_token}}

###
GET http://{{origin}}{{api_prefix}}/workspace?id=1
Authorization: Bearer {{auth_token}}

###
POST http://{{origin}}{{api_prefix}}/workspace
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "tuke's workspace",
  "description": "test workspace"
}

###
PUT http://{{origin}}{{api_prefix}}/workspace
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 1,
  "name": "tuke's workspace",
  "description": "test workspace!"
}