GET http://{{origin}}{{api_prefix}}/workflow?id=1

###
# python -c "import uuid; print(uuid.uuid4())"
POST http://{{origin}}{{api_prefix}}/workflow
Content-Type: application/json

< ./workflow_demo1.json


###
POST http://{{origin}}{{api_prefix}}/workflow
Content-Type: application/json

< ./workflow_demo2.json
