GET http://{{origin}}{{api_prefix}}/workflow?id=1

###
GET http://{{origin}}{{api_prefix}}/workflow?id=2

###
POST http://{{origin}}{{api_prefix}}/workflow
Content-Type: application/json

< ./workflow_demo1.json


###
POST http://{{origin}}{{api_prefix}}/workflow
Content-Type: application/json

< ./workflow_demo2.json
