###
# Model LLM
GET {{URL_PREFIX}}/meta/model/providers?model_type=llm
Authorization: Bearer {{auth_token}}

###
# Model TextEmbedding
GET {{URL_PREFIX}}/meta/model/providers?model_type=text_embedding
Authorization: Bearer {{auth_token}}

###
# VectorStore
GET {{URL_PREFIX}}/meta/vector-store/providers
Authorization: Bearer {{auth_token}}

###
# Storage
GET {{URL_PREFIX}}/meta/storage/providers
Authorization: Bearer {{auth_token}}
