###
# Model List
GET {{URL_PREFIX}}/model/list
Authorization: Bearer {{auth_token}}

###
# Model Get 1
GET {{URL_PREFIX}}/model?id=1
Authorization: Bearer {{auth_token}}

###
# Model Get 2
GET {{URL_PREFIX}}/model?id=2
Authorization: Bearer {{auth_token}}

###
# Model Create Ollama
POST {{URL_PREFIX}}/model
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "type": "llm",
  "name": "llm - ollama - qwen3:4b",
  "provider_name": "ollama",
  "model_name": "qwen3:4b",
  "config": {
    "base_url": "http://{{OLLAMA_HOST}}:11434",
    "function_calling": true
  }
}

###
# Model Create TextEmbedding
POST {{URL_PREFIX}}/model
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "type": "text_embedding",
  "name": "text_embedding - ollama - qwen3:4b",
  "provider_name": "ollama",
  "model_name": "qwen3:4b",
  "config": {
    "base_url": "http://{{OLLAMA_HOST}}:11434"
  }
}

###
# Model Update
PUT {{URL_PREFIX}}/model
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 2,
  "model_name": "qwen3:4b",
  "config": {
    "timeout": 20
  }
}

###
# Model Update Enable
POST {{URL_PREFIX}}/model/update-enable?id=1
Authorization: Bearer {{auth_token}}

###
# Model Test Run
POST {{URL_PREFIX}}/model/test-run
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 1,
  "prompt": "帮忙写段提示语ABCD，请注意，用户是一个中国古诗词爱好者，用户想要提问问关于古诗词的问题作为LLM的提示词，但是他的问题可能没有表述好，你需要写一段提示词ABCD给用户，然后用户会将ABCD作为提示词去给LLM，以让LLM帮忙优化他的提示词。请问，这里的ABCD该如何设计？请输出具体的ABCD提示词，并给出优化建议"
}

###
# Model Default LLM
GET {{URL_PREFIX}}/model/default?model_type=llm
Authorization: Bearer {{auth_token}}

###
# Model Default TextEmbedding
GET {{URL_PREFIX}}/model/default?model_type=text_embedding
Authorization: Bearer {{auth_token}}

###
# Model Default LLM Setup
POST {{URL_PREFIX}}/model/default
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "model_type": "llm",
  "model_id": 1
}

###
# Model Default TextEmbedding Setup
POST {{URL_PREFIX}}/model/default
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "model_type": "text_embedding",
  "model_name": "all-MiniLM-L6-v2"
}
