GET {{url_prefix}}/storage/list
Authorization: Bearer {{auth_token}}

###
GET {{url_prefix}}/storage?id=1
Authorization: Bearer {{auth_token}}

###
GET {{url_prefix}}/storage?id=2
Authorization: Bearer {{auth_token}}

###
POST {{url_prefix}}/storage
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "opendal storage",
  "type": "opendal",
  "config": {
    "endpoint": "{{OPENDAL_ENDPOINT}}",
    "region": "{{OPENDAL_REGION}}",
    "access_key": "{{OPENDAL_ACCESS_KEY}}",
    "secret_key": "{{OPENDAL_SECRET_KEY}}"
  }
}

###
POST {{url_prefix}}/storage
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "s3 storage",
  "type": "s3",
  "config": {
    "endpoint": "{{S3_ENDPOINT}}",
    "region": "{{S3_REGION}}",
    "access_key": "{{S3_ACCESS_KEY}}",
    "secret_key": "{{S3_SECRET_KEY}}"
  }
}

###
GET {{url_prefix}}/storage/default
Authorization: Bearer {{auth_token}}

###
POST {{url_prefix}}/storage/default
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "storage_id": 1
}