###
# Access Token Create
POST {{URL_PREFIX}}/auth/access-token
Content-Type: application/x-www-form-urlencoded

username=tinyrag@dreamcat.org&password=tinyrag

> {% client.global.set("auth_token", response.body.data.access_token); %}

###
# User List
GET {{URL_PREFIX}}/user/list
Authorization: Bearer {{auth_token}}

###
# User Get
GET {{URL_PREFIX}}/user?email=tinyrag@dreamcat.org
Authorization: Bearer {{auth_token}}

###
# User Create
POST {{URL_PREFIX}}/user
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "email": "tuke@dreamcat.org",
  "password": "tuke"
}
