GET {{URL_PREFIX}}/vector-store/list
Authorization: Bearer {{auth_token}}

###
GET {{URL_PREFIX}}/vector-store?id=1
Authorization: Bearer {{auth_token}}

###
GET {{URL_PREFIX}}/vector-store?id=2
Authorization: Bearer {{auth_token}}

###
GET {{URL_PREFIX}}/vector-store?id=3
Authorization: Bearer {{auth_token}}

###
GET {{URL_PREFIX}}/vector-store?id=4
Authorization: Bearer {{auth_token}}

###
POST {{URL_PREFIX}}/vector-store
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "chroma vector store",
  "type": "chroma",
  "config": {
    "host": "*"
  }
}

###
POST {{URL_PREFIX}}/vector-store
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "qdrant vector store",
  "type": "qdrant",
  "config": {
    "url": "*"
  }
}

###
POST {{URL_PREFIX}}/vector-store
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "pgvector vector store",
  "type": "pgvector",
  "config": {
    "host": "{{PGVECTOR_HOST}}",
    "port": "{{PGVECTOR_PORT}}",
    "user": "{{PGVECTOR_USER}}",
    "password": "{{PGVECTOR_PASSWORD}}",
    "database": "{{PGVECTOR_DB_NAME}}"
  }
}

###
POST {{URL_PREFIX}}/vector-store
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "milvus vector store",
  "type": "milvus",
  "config": {
    "uri": "{{MILVUS_URI}}",
    "user": "{{MILVUS_USER}}",
    "password": "{{MILVUS_PASSWORD}}",
    "db_name": "{{MILVUS_DB_NAME}}"
  }
}


###
GET {{URL_PREFIX}}/vector-store/default
Authorization: Bearer {{auth_token}}

###
POST {{URL_PREFIX}}/vector-store/default
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "vector_store_id": 1
}