GET http://{{origin}}{{api_prefix}}/file?id={{file_id}}
Authorization: Bearer {{auth_token}}

###
GET http://{{origin}}{{api_prefix}}/file?id={{file_id_json_list}}
Authorization: Bearer {{auth_token}}

###
GET http://{{origin}}{{api_prefix}}/file/upload
Authorization: Bearer {{auth_token}}

###
# curl -F "file=@/path/to/file" http://127.0.0.1:8000/api/v1/file/upload?workspace_id=1
# ../../sql/ddl_base.sql
# ../../../workdir/uploads/quantangshi/poet.tang.0.json
POST http://{{origin}}{{api_prefix}}/file/upload?workspace_id=1
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="some.file"
Content-Type: application/json

< ../../sql/ddl_base.sql
--WebAppBoundary--

> {% client.global.set("file_id", response.body.data.id); %}
