GET http://{{origin}}{{api_prefix}}/knowledge/list?workspace_id=1
Authorization: Bearer {{auth_token}}

###
GET http://{{origin}}{{api_prefix}}/knowledge?id=1
Authorization: Bearer {{auth_token}}

###
# 全唐诗
POST http://{{origin}}{{api_prefix}}/knowledge
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "workspace_id": 1,
  "name": "空白知识库",
  "description": "some description"
}

###
PUT http://{{origin}}{{api_prefix}}/knowledge
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 1,
  "name": "全唐诗",
  "description": "资源来源：https://github.com/chinese-poetry/chinese-poetry"
}

###
POST http://{{origin}}{{api_prefix}}/knowledge/config
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 1,
  "process_rule": {
    "text_splitter": {
      "chunk_overlap": 50,
      "chunk_size": 256,
      "separators": [
        "}"
      ]
    }
  }
}

###
POST http://{{origin}}{{api_prefix}}/knowledge/preview-chunk
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "file_id": "{{file_id}}",
  "process_rule": {
    "text_splitter": {
      "chunk_overlap": 50,
      "chunk_size": 256,
      "separators": [
        "create table"
      ]
    }
  }
}

###
POST http://{{origin}}{{api_prefix}}/knowledge/import
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 1,
  "file": {
    "file_ids": [
      "{{file_id}}"
    ]
  }
}

###
POST http://{{origin}}{{api_prefix}}/knowledge/import
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 1,
  "storage": {
    "file_path": "chinese-poetry/quantangshi/"
  }
}

> {% client.global.set("task_id", response.body.data.id); %}

###
GET http://{{origin}}{{api_prefix}}/task?id={{task_id}}
Authorization: Bearer {{auth_token}}
